[2025-06-07T19:32:06.885+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: producer_dag.run_producer_one_file scheduled__2025-06-07T19:00:00+00:00 [queued]>
[2025-06-07T19:32:06.891+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: producer_dag.run_producer_one_file scheduled__2025-06-07T19:00:00+00:00 [queued]>
[2025-06-07T19:32:06.892+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2025-06-07T19:32:06.900+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_producer_one_file> on 2025-06-07 19:00:00+00:00
[2025-06-07T19:32:06.903+0000] {standard_task_runner.py:60} INFO - Started process 253 to run task
[2025-06-07T19:32:06.905+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'producer_dag', 'run_producer_one_file', 'scheduled__2025-06-07T19:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpfg4elxey']
[2025-06-07T19:32:06.906+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask run_producer_one_file
[2025-06-07T19:32:06.928+0000] {task_command.py:423} INFO - Running <TaskInstance: producer_dag.run_producer_one_file scheduled__2025-06-07T19:00:00+00:00 [running]> on host 660bb7972175
[2025-06-07T19:32:06.962+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='panshul' AIRFLOW_CTX_DAG_ID='producer_dag' AIRFLOW_CTX_TASK_ID='run_producer_one_file' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-07T19:00:00+00:00'
[2025-06-07T19:32:06.962+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-07T19:32:06.963+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/kafka_client/producer_one_shot.py']
[2025-06-07T19:32:06.967+0000] {subprocess.py:86} INFO - Output:
[2025-06-07T19:32:07.233+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-07T19:32:07.233+0000] {subprocess.py:93} INFO -   File "/opt/***/kafka_client/producer_one_shot.py", line 6, in <module>
[2025-06-07T19:32:07.233+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-06-07T19:32:07.233+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-06-07T19:32:07.279+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-07T19:32:07.285+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-07T19:32:07.287+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=producer_dag, task_id=run_producer_one_file, execution_date=20250607T190000, start_date=20250607T193206, end_date=20250607T193207
[2025-06-07T19:32:07.293+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task run_producer_one_file (Bash command failed. The command returned a non-zero exit code 1.; 253)
[2025-06-07T19:32:07.336+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-07T19:32:07.347+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
