[2025-06-08T14:20:06.179+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T14:20:06.203+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_pipeline_with_es_guard.fail_if_es_down_too_long scheduled__2025-06-08T13:30:00+00:00 [queued]>
[2025-06-08T14:20:06.210+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_pipeline_with_es_guard.fail_if_es_down_too_long scheduled__2025-06-08T13:30:00+00:00 [queued]>
[2025-06-08T14:20:06.210+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-08T14:20:06.225+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fail_if_es_down_too_long> on 2025-06-08 13:30:00+00:00
[2025-06-08T14:20:06.232+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'master_pipeline_with_es_guard', 'fail_if_es_down_too_long', 'scheduled__2025-06-08T13:30:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmps205vsaq']
[2025-06-08T14:20:06.234+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1938) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-08T14:20:06.235+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask fail_if_es_down_too_long
[2025-06-08T14:20:06.235+0000] {standard_task_runner.py:63} INFO - Started process 1941 to run task
[2025-06-08T14:20:06.273+0000] {task_command.py:426} INFO - Running <TaskInstance: master_pipeline_with_es_guard.fail_if_es_down_too_long scheduled__2025-06-08T13:30:00+00:00 [running]> on host 5492e8ecb5c1
[2025-06-08T14:20:06.331+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='panshul' AIRFLOW_CTX_DAG_ID='master_pipeline_with_es_guard' AIRFLOW_CTX_TASK_ID='fail_if_es_down_too_long' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T13:30:00+00:00'
[2025-06-08T14:20:06.332+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T14:20:06.343+0000] {logging_mixin.py:188} INFO - ðŸ“Š ES failure count: 1
[2025-06-08T14:20:06.344+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-08T14:20:06.344+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T14:20:06.352+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=master_pipeline_with_es_guard, task_id=fail_if_es_down_too_long, run_id=scheduled__2025-06-08T13:30:00+00:00, execution_date=20250608T133000, start_date=20250608T142006, end_date=20250608T142006
[2025-06-08T14:20:06.374+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-08T14:20:06.389+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-08T14:20:06.391+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
